### ISSUE TITLE
Do not constantly use Stds. Nested for loops?

### ISSUE THREAD

**Issue by HatBreakingDad** [brcheese/spiralGE#1]
I know you like the look of std::cout and what not, but it is not necessarily suitable for your project and actually results in longer compiling time.
Instead use namespace std.
You may be Aspergers for it but it doesn't mean it is the best choice.
Also check out the boost c++ libraries. They are good for mathematical calculations and compressing nested for loops. It would be good for your type of project.

**Comment by Ilikescheese** [comment]
`using namespace std;` causes namespace pollution, you generally don't want that when making something this big. Consider you wanted to make your own list class for example, you'd be overloading std::list which could be used later for some listing function in another header file. Finally, it doesn't make a difference in compile time with or without `using namespace std;`

I do agree with you on boost though. Eventually, I will need a API agnostic math library for when it comes to things like directX and vulkan for 3d transformations and such.

**Comment by SamGenieBoi** [comment]
Tthis kid is wrong!&^^^^^^^

**Comment by Ilikescheese** [comment]
^this kid is rong
